Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "chef/centos-7.1"
  c.vm.hostname = "default-centos71"
    c.ssh.username = "root"
    c.ssh.password = "vagrant"
  c.vm.network(:private_network, {:ip=>"192.168.56.40"})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "/Users/ndodakheswa/chef-kits", "/mnt/share", disabled: false
  c.vm.provider :virtualbox do |p|
    p.customize ["modifyvm", :id, "--cpus", "1"]
    p.customize ["modifyvm", :id, "--memory", "1024"]
  end
end
